spring:
  mvc:  
    view:  
      prefix: /WEB-INF/views/
      suffix: .jsp

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mercari
    username: postgres
    password: postgres
    
  batch.initialize-schema: always
  batch.job.enabled: true